- name: "Install openssl module"
  dnf:
    name: python3-pyOpenSSL
    state: installed

- name: "Generate Private Key"
  community.crypto.openssl_privatekey:
      path: "/etc/ssl/certs/{{ ansible_fqdn }}.key"
      size: 4096
      type: DSA
      backup: yes

- name: "Generate Certificate Request with private key"
  community.crypto.openssl_csr:
        path: "/etc/ssl/certs/{{ ansible_fqdn }}.crt"
        privatekey_path: "/etc/ssl/certs/{{ ansible_hostname }}.key"
        country_name: "{{ country_name }}"
        organization_name: "{{ organization_name }}"
        email_address: "{{ email_address }}"
        common_name: "{{ ansible_fqdn }}"

- name: "Generating Self Signed Certificate"
  community.crypto.x509_certificate:
        path: "/etc/ssl/certs/{{ ansible_fqdn }}_cer"
        privatekey_path: "/etc/ssl/certs/{{ ansible_fqdn }}.key"
        csr_path: "/etc/ssl/certs/{{ ansible_fqdn }}.crt"
        provider: selfsigned
