- name: Add repository
  yum_repository:
     name: Prometheus
     description: Prometheus Exporter Repo
     baseurl: https://packagecloud.io/prometheus-rpm/release/el/$releasever/$basearch
     gpgcheck: yes 
     enabled: yes 
     gpgkey: 
         - https://packagecloud.io/prometheus-rpm/release/gpgkey
         - https://raw.githubusercontent.com/lest/prometheus-rpm/master/RPM-GPG-KEY-prometheus-rpm
     metadata_expire: 300

